name: Manual MQTT.js CI 

on:
  watch:
    types: [started]


jobs:
  build:

    runs-on: ubuntu-latest
    
    if: github.actor == github.event.repository.owner.login

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        DEBUG: "mqttjs*"
